#### Задание 1

In [11]:
import numpy as np
a = np.array([[1,2,3,3,1],
             [6,8,11,10,7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

#### Задание 2

In [15]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3

In [23]:
a_centered_sp = a_centered[0:5,0] @ a_centered[0:5,1]
a_centered_sp

8.0

In [32]:
N = a.shape[0]
a_centered_sp / (N-1)

2.0

#### Задание 4**

In [35]:
cov_a = np.cov(a.T)
cov_a

array([[1. , 2. ],
       [2. , 4.3]])

In [36]:
cov_a[0,1]

2.0